# Define how Bash prompt looks like:
#
# User @ Host – working dir
export PS1="\h\w$a "

# history handling
#
# Erase duplicates
export HISTCONTROL=erasedups
# resize history size
export HISTSIZE=10000000
# resize history file size
export HISTFILESIZE=10000000
# append to bash_history if Terminal.app quits
shopt -s histappend

# locales
#
# http://askubuntu.com/questions/412495/setlocale-lc-ctype-cannot-change-locale-utf-8
#export LANG=ja_JP.UTF-8
export LANG=en_US.UTF-8
#export LC_ALL=ja_JP.UTF-8
export LC_ALL=en_US.UTF-8
# some problems with gems http://stackoverflow.com/questions/4975973/gem-update-unable-to-convert-xe7-to-utf-8-in-conversion-from-ascii-8bit-to-u
export LC_CTYPE="utf-8"

# default editor
#
export EDITOR='nano'

# rbenv
#
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# PATH
#export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
