---
- name: Install Casks
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ cask_packages }}"

- name: install CLI tools after cask dependencies
  homebrew: name={{ item }} state=present
  with_items: "{{ brew_packages_after_cask }}"
