- name: install rbenv
  homebrew: name={{ item }} state=present
  with_items:
    - rbenv
    - ruby-build

- name: install ruby 2.3.0
  command: rbenv install -s 2.3.0

- name: set global ruby version
  command: rbenv global 2.3.0
