- name: install rbenv
  homebrew: name={{ item }} state=present
  with_items:
    - rbenv
    - ruby-build

- name: install ruby 2.4.3
  command: rbenv install -s 2.4.3

- name: set global ruby version
  command: rbenv global 2.4.3

- name: init rbenv
  shell: if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

- name: update rubygems
  shell: gem update --system
  become: yes
